SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

DROP TABLE IF EXISTS rooms;
CREATE TABLE IF NOT EXISTS rooms (
  rid varchar(100) NOT NULL,
  phone varchar(4) NOT NULL,
  `comment` varchar(200) NOT NULL,
  PRIMARY KEY (rid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

