var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "d L yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W d/M",
            "Md3": "d L",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "dim.",
            "mon": "lundi",
            "tue": "mardi",
            "wed": "mercr.",
            "thu": "jeudi",
            "fri": "vendr.",
            "sat": "sam.",
            "jan": "janv.",
            "feb": "fevr.",
            "mar": "mars",
            "apr": "avril",
            "may": "mai",
            "jun": "juin",
            "jul": "juill.",
            "aug": "août",
            "sep": "sept.",
            "oct": "oct.",
            "nov": "nov.",
            "dec": "dec."
        },
        "no_implemented": "Pas encore implémenté",
        "to_date_view": "Voir les activités du jour",
        "i_undefined": "Undefined",
        "allday_event": "Toute la journée",
        "repeat_event": "Évènement régulier",
        "time": "Date",
        "event": "Évènement",
        "location": "Description",
        "participant": "Participant",
        "get_data_exception": "Exception when getting data",
        "new_event": "New event",
        "confirm_delete_event": "Do you confirm to delete this event? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "Event title can not be blank or contains ($<>)",
        "view_no_ready": "View is not ready",
        "example": "e.g., meeting at room 107",
        "content": "Contenu :",
        "create_event": "Create event",
        "update_detail": "Edit details",
        "click_to_detail": "Voir les détails",
        "i_delete": "Delete",
        "day_plural": "jours",
        "others": "Autres",
        "item": ""
    }
});
